//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5RQ.Areas.Scripts {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptPack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptPack() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvc5RQ.Areas.Scripts.ScriptPack", typeof(ScriptPack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;form id=&quot;add-user-form&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;legend&gt;Add User&lt;/legend&gt;
        ///	&lt;!--&lt;div id=&quot;basic-user-info&quot;&gt;--&gt;
        ///		&lt;div class=&quot;editor-label&quot;&gt;
        ///			&lt;label for=&quot;tbx-add-username&quot;&gt;
        ///				Name&lt;/label&gt;
        ///		&lt;/div&gt;
        ///		&lt;div class=&quot;editor-field&quot;&gt;
        ///			&lt;input type=&quot;text&quot; id=&quot;tbx-add-username&quot; placeholder=&quot;e.g. John&quot;/&gt;&lt;/div&gt;
        ///		&lt;div class=&quot;editor-label&quot;&gt;
        ///			&lt;label for=&quot;tbx-add-password&quot;&gt;
        ///				Password&lt;/label&gt;
        ///		&lt;/div&gt;
        ///		&lt;div class=&quot;editor-field&quot;&gt;
        ///			&lt;input type=&quot;password&quot; id=&quot;tbx-add-password&quot; placeholder=&quot;password&quot;/&gt;
        ///		&lt;/div&gt;
        ///		&lt;div class=&quot;e [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string add_user_form {
            get {
                return ResourceManager.GetString("add_user_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;form id=&quot;classtree-options-form&quot; class=&quot;pure-form-aligned&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;label for=&quot;classtree-options&quot;&gt;
        ///		{classtree-options}&lt;/label&gt;
        ///	&lt;input id=&quot;classtree-options&quot; type=&quot;checkbox&quot; /&gt;&lt;br/&gt;
        ///&lt;!--    &lt;a class=&quot;select-databases&quot; href=&quot;#&quot;&gt;{select-databases}&lt;/a&gt;--&gt;
        ///&lt;/fieldset&gt;
        ///&lt;/form&gt;
        /// ähnelt.
        /// </summary>
        internal static string classtree_options_form {
            get {
                return ResourceManager.GetString("classtree_options_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () {
        ///    var onlyShelvesCheckBox = new AddOnlyShelvesCheckBox();
        ///    onlyShelvesCheckBox.init(&quot;#classtree-options&quot;);
        ///    
        ///    //$(&quot;.select-databases&quot;).on(&quot;click&quot;, selectDatabases);
        ///});
        ///
        ///function AddOnlyShelvesCheckBox() {
        ///    var checkBox;
        ///
        ///    /* Initialize the only shelves check box and fill it with server data */
        ///    this.init = function (selector) {
        ///        // get check box
        ///        checkBox = $(selector);
        ///        // init the check box with server data  
        ///        $.post(HostAdres [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string classtree_options_management {
            get {
                return ResourceManager.GetString("classtree_options_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;form id=&quot;include-external-db-form&quot; class=&quot;pure-form-aligned&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;label for=&quot;include-external&quot;&gt;
        ///		{include-external}&lt;/label&gt;
        ///	&lt;input id=&quot;include-external&quot; type=&quot;checkbox&quot; /&gt;&lt;br/&gt;
        ///    &lt;a class=&quot;select-databases&quot; href=&quot;#&quot;&gt;{select-databases}&lt;/a&gt;
        ///&lt;/fieldset&gt;
        ///&lt;/form&gt;
        /// ähnelt.
        /// </summary>
        internal static string imclude_external_db_form {
            get {
                return ResourceManager.GetString("imclude_external_db_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        ///* TableSorter 2.0 - Client-side table sorting with ease!
        ///* Version 2.0.28 Minified using http://dean.edwards.name/packer/
        ///* Copyright (c) 2007 Christian Bach
        ///*/
        ///
        ///!(function ($) { $.extend({ tablesorter: new function () { var g = [], widgets = [], tbl; this.defaults = { cssHeader: &quot;header&quot;, cssAsc: &quot;headerSortUp&quot;, cssDesc: &quot;headerSortDown&quot;, cssChildRow: &quot;expand-child&quot;, sortInitialOrder: &quot;asc&quot;, sortMultiSortKey: &quot;shiftKey&quot;, sortForce: null, sortAppend: null, sortLocaleCompare: false, textExtraction: &quot;simpl [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_tablesorter_min {
            get {
                return ResourceManager.GetString("jquery_tablesorter_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;form id=&quot;manage-roles-form&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;legend&gt;Manage Roles&lt;/legend&gt;
        ///	&lt;div class=&quot;editor-label&quot;&gt;
        ///		&lt;label for=&quot;role-name&quot;&gt;
        ///			Rolename&lt;/label&gt;&lt;/div&gt;
        ///	&lt;div class=&quot;editor-field&quot;&gt;
        ///		&lt;input type=&quot;text&quot; id=&quot;role-name&quot; placeholder=&quot;e.g. test&quot; /&gt;&lt;/div&gt;
        ///	&lt;input type=&quot;button&quot; id=&quot;btn-add-role&quot; value=&quot;Add Role&quot; /&gt;
        ///	&lt;div class=&quot;editor-label&quot;&gt;
        ///		All roles&lt;/div&gt;
        ///	&lt;div class=&quot;editor-field&quot;&gt;
        ///		&lt;select id=&quot;add-user-roles&quot; size=&quot;10&quot; class=&quot;role-select-box&quot;&gt;
        ///		&lt;/select&gt;
        ///	&lt;/div&gt;
        ///	&lt;label for=&quot;allow-populated-role&quot;&gt;
        ///		Allow  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string manage_roles_form {
            get {
                return ResourceManager.GetString("manage_roles_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var myInterval = false; // this variable will hold the interval and work as a flag
        ///var $win = $(window); //jquery win object
        ///var dimensions = [$win.width(), $win.height()]; //initial dimensions
        ///
        ///$(function () {
        ///    $(window).on(&quot;debouncedresize&quot;, function (event) {
        ///        dimensions[0] = $win.width(); //else keep the new dimensions
        ///        dimensions[1] = $win.height();
        ///        resizeToWindowHeight();
        ///    });
        ///});
        ///
        ///function resizeToWindowHeight() {
        ///    var height = dimensions[1] - 60;
        ///    var  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string rqui_helpers {
            get {
                return ResourceManager.GetString("rqui_helpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () {
        ///    var includeExternalCheckBox = new AddIncludeExternalCheckBox();
        ///    includeExternalCheckBox.init(&quot;#include-external&quot;);
        ///    
        ///    $(&quot;.select-databases&quot;).on(&quot;click&quot;, selectDatabases);
        ///});
        ///
        ///function AddIncludeExternalCheckBox() {
        ///    var checkBox;
        ///
        ///    /* Initialize the include external check box and fill it with server data */
        ///    this.init = function (selector) {
        ///        // get check box
        ///        checkBox = $(selector);
        ///        // init the check box with server data  
        ///        [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string simple_query_options_management {
            get {
                return ResourceManager.GetString("simple_query_options_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///$(function () {
        ///
        ///  var addUserArea = new AddUserArea();
        ///  addUserArea.init(&quot;.simple-user-table&quot;);
        ///
        ///  var roleMgmt = new RoleManagement();
        ///  roleMgmt.init();
        ///
        ///  var userTableArea = new UserTableArea();
        ///  userTableArea.init(&quot;.simple-user-table&quot;);
        ///
        ///});
        ///
        ///function UserTableArea() {
        ///
        ///  var userTable;
        ///
        ///  /* Initializes the user table and fills it with server data. */
        ///  this.init = function (tableSelector) {
        ///
        ///    // get user table
        ///    userTable = $(tableSelector);
        ///
        ///    // fill the user tabl [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string simple_user_management {
            get {
                return ResourceManager.GetString("simple_user_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*#simple-user-info {
        ///  padding: 15px 0;
        ///  text-align: center;
        ///  background-repeat: no-repeat;
        ///  background-position: 10px center;
        ///  position: relative;
        ///  color: #00529B;
        ///  position: fixed;
        ///  top: 0;
        ///  width: 100%;
        ///  filter: alpha(opacity=95);
        ///  -moz-opacity: 0.95;
        ///  opacity: 0.95;
        ///}
        ///
        ///#simple-user-info.error {
        ///  background-color: Yellow;
        ///}
        ///
        ///#simple-user-info.success {
        ///  background-color: Lime;
        ///}*/
        ///
        ///#add-user-form, #manage-roles-form {
        ///  display: inline-block;
        ///}
        ///
        ///.select-databases- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        ///* tablesorter pager plugin
        ///* updated 1/31/2012
        ///*/
        ///
        ///(function ($) {
        ///  $.extend({ tablesorterPager: new function () {
        ///
        ///    // hide arrows at extremes
        ///    var pagerArrows = function (c) {
        ///      var a = &apos;addClass&apos;, r = &apos;removeClass&apos;, d = c.cssDisabled;
        ///      if (c.updateArrows) {
        ///        c.container[(c.totalRows &lt; c.size) ? a : r](d);
        ///        $(c.cssFirst + &apos;,&apos; + c.cssPrev, c.container)[(c.page === 0) ? a : r](d);
        ///        $(c.cssNext + &apos;,&apos; + c.cssLast, c.container)[(c.page === c.totalPages - 1) ? a : r](d);
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string tablesorter_pager {
            get {
                return ResourceManager.GetString("tablesorter_pager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (function (a) { a.extend({ tablesorterPager: new function () { var b = function (b) { var c = &quot;addClass&quot;, d = &quot;removeClass&quot;, e = b.cssDisabled; if (b.updateArrows) { b.container[b.totalRows &lt; b.size ? c : d](e); a(b.cssFirst + &quot;,&quot; + b.cssPrev, b.container)[b.page === 0 ? c : d](e); a(b.cssNext + &quot;,&quot; + b.cssLast, b.container)[b.page === b.totalPages - 1 ? c : d](e) } }, c = function (c, d) { d.startRow = d.size * d.page + 1; d.endRow = Math.min(d.totalRows, d.size * (d.page + 1)); var e = a(d.cssPageDisplay, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string tablesorter_pager_min {
            get {
                return ResourceManager.GetString("tablesorter_pager_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /* tables */
        ///.simple-user-table {
        ///	background-color: #CDCDCD;
        ///	margin:10px 0pt 15px;
        ///	width: 100%;
        ///	text-align: left;
        ///}
        ///.simple-user-table thead tr th, .simple-user-table tfoot tr th {
        ///	background-color: #e6EEEE !important;
        ///	border: 1px solid #FFF;
        ///	padding: 4px;
        ///}
        ///.simple-user-table thead tr .header {
        ///	cursor: pointer;
        ///}
        ///.simple-user-table tbody td {
        ///	
        ///	padding: 4px;
        ///	background-color: #FFF;
        ///	vertical-align: top;
        ///}
        ///.simple-user-table tbody tr.odd td {
        ///	background-color:#F0F0F6;
        ///}
        ///.simple-user-table thead t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string tablesorter_style {
            get {
                return ResourceManager.GetString("tablesorter_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;fieldset class=&quot;simple-user-table-field&quot;&gt;
        ///&lt;legend&gt;User Table&lt;/legend&gt;
        ///	&lt;table class=&apos;simple-user-table tablesorter&apos;&gt;
        ///		&lt;thead&gt;
        ///			&lt;tr&gt;
        ///				&lt;th class=&quot;user-id&quot;&gt;
        ///					ID
        ///				&lt;/th&gt;
        ///				&lt;th class=&quot;user-name&quot;&gt;
        ///					Name
        ///				&lt;/th&gt;
        ///				&lt;th class=&quot;reg-date&quot;&gt;
        ///					Registration
        ///				&lt;/th&gt;
        ///				&lt;th class=&quot;email&quot;&gt;
        ///					E-Mail
        ///				&lt;/th&gt;
        ///				&lt;th class=&quot;lock-state&quot;&gt;
        ///					LockIn/Out
        ///				&lt;/th&gt;
        ///				&lt;th class=&quot;edit-roles&quot;&gt;
        ///					Roles
        ///				&lt;/th&gt;
        ///				&lt;th class=&quot;action&quot;&gt;
        ///					Action
        ///				&lt;/th&gt;
        ///			&lt;/tr&gt;
        ///		&lt;/thead&gt;
        ///		&lt;tbody&gt;
        ///		&lt;/tbod [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string user_table_area {
            get {
                return ResourceManager.GetString("user_table_area", resourceCulture);
            }
        }
    }
}
