//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5RQ.Areas.DigitalObjects {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptPack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptPack() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvc5RQ.Areas.DigitalObjects.ScriptPack", typeof(ScriptPack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;div id=&quot;viewer_area&quot;&gt;
        /// &lt;div id=&quot;jquery_jplayer_1&quot; class=&quot;jp-jplayer&quot;&gt;&lt;/div&gt;
        ///  &lt;div id=&quot;jp_container_1&quot; class=&quot;jp-audio&quot;&gt;
        ///    &lt;div class=&quot;jp-type-single&quot;&gt;
        ///      &lt;div class=&quot;jp-gui jp-interface&quot;&gt;
        ///        &lt;ul class=&quot;jp-controls&quot;&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript:;&quot; class=&quot;jp-play&quot; tabindex=&quot;1&quot;&gt;play&lt;/a&gt;&lt;/li&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript:;&quot; class=&quot;jp-pause&quot; tabindex=&quot;1&quot;&gt;pause&lt;/a&gt;&lt;/li&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript:;&quot; class=&quot;jp-stop&quot; tabindex=&quot;1&quot;&gt;stop&lt;/a&gt;&lt;/li&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string audio_player {
            get {
                return ResourceManager.GetString("audio_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;div id=&quot;viewer_area&quot;&gt;
        /// &lt;div id=&quot;jquery_jplayer_1&quot; class=&quot;jp-jplayer&quot;&gt;&lt;/div&gt;
        ///  &lt;div id=&quot;jp_container_1&quot; class=&quot;jp-audio&quot;&gt;
        ///    &lt;div class=&quot;jp-type-single&quot;&gt;
        ///      &lt;div class=&quot;jp-gui jp-interface&quot;&gt;
        ///        &lt;ul class=&quot;jp-controls&quot;&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript:;&quot; class=&quot;jp-play&quot; tabindex=&quot;1&quot;&gt;play&lt;/a&gt;&lt;/li&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript:;&quot; class=&quot;jp-pause&quot; tabindex=&quot;1&quot;&gt;pause&lt;/a&gt;&lt;/li&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript:;&quot; class=&quot;jp-stop&quot; tabindex=&quot;1&quot;&gt;stop&lt;/a&gt;&lt;/li&gt;
        ///          &lt;li&gt;&lt;a href=&quot;javascript [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string audio_playlist {
            get {
                return ResourceManager.GetString("audio_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;div id=&quot;viewer_area&quot;&gt;&lt;/div&gt;
        /// ähnelt.
        /// </summary>
        internal static string item_viewer_bib_info {
            get {
                return ResourceManager.GetString("item_viewer_bib_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * Skin for jPlayer Plugin (jQuery JavaScript Library)
        /// * http://www.jplayer.org
        /// *
        /// * Skin Name: Blue Monday
        /// *
        /// * Copyright (c) 2010-2012 Happyworm Ltd
        /// * Dual licensed under the MIT and GPL licenses.
        /// *  - http://www.opensource.org/licenses/mit-license.php
        /// *  - http://www.gnu.org/copyleft/gpl.html
        /// *
        /// * Author: Silvia Benvenuti
        /// * Skin Version: 4.3 (jPlayer 2.2.0)
        /// * Date: 19th November 2012
        /// */
        ///
        ///div.jp-audio,
        ///div.jp-audio-stream,
        ///div.jp-video {
        ///
        ///	/* Edit the font-size to countera [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jplayer_blue_monday {
            get {
                return ResourceManager.GetString("jplayer_blue_monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * Skin for jPlayer Plugin (jQuery JavaScript Library)
        /// * http://www.jplayer.org
        /// *
        /// * Skin Name: Pink Flag
        /// *
        /// * Copyright (c) 2012 Happyworm Ltd
        /// * Dual licensed under the MIT and GPL licenses.
        /// *  - http://www.opensource.org/licenses/mit-license.php
        /// *  - http://www.gnu.org/copyleft/gpl.html
        /// *
        /// * Author: Silvia Benvenuti
        /// * Skin Version: 1.2 (jPlayer 2.2.0)
        /// * Date: 22nd October 2012
        /// */
        ///
        ///div.jp-audio,
        ///div.jp-audio-stream,
        ///div.jp-video {
        ///
        ///	/* Edit the font-size to counteract inherited font sizing.
        ///	  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jplayer_pink_flag {
            get {
                return ResourceManager.GetString("jplayer_pink_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * Playlist Object for the jPlayer Plugin
        /// * http://www.jplayer.org
        /// *
        /// * Copyright (c) 2009 - 2013 Happyworm Ltd
        /// * Dual licensed under the MIT and GPL licenses.
        /// *  - http://www.opensource.org/licenses/mit-license.php
        /// *  - http://www.gnu.org/copyleft/gpl.html
        /// *
        /// * Author: Mark J Panaghiston
        /// * Version: 2.3.0
        /// * Date: 20th April 2013
        /// *
        /// * Requires:
        /// *  - jQuery 1.7.0+
        /// *  - jPlayer 2.3.0+
        /// */
        ///
        ////* Code verified using http://www.jshint.com/ */
        ////*jshint asi:false, bitwise:false, boss: [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jplayer_playlist {
            get {
                return ResourceManager.GetString("jplayer_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * Playlist Object for the jPlayer Plugin
        /// * http://www.jplayer.org
        /// *
        /// * Copyright (c) 2009 - 2013 Happyworm Ltd
        /// * Dual licensed under the MIT and GPL licenses.
        /// *  - http://www.opensource.org/licenses/mit-license.php
        /// *  - http://www.gnu.org/copyleft/gpl.html
        /// *
        /// * Author: Mark J Panaghiston
        /// * Version: 2.3.0
        /// * Date: 20th April 2013
        /// *
        /// * Requires:
        /// *  - jQuery 1.7.0+
        /// *  - jPlayer 2.3.0+
        /// */
        ///(function(b,f){jPlayerPlaylist=function(a,c,d){var e=this;this.current=0;this.removing=this.shuffled=this.loo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jplayer_playlist_min {
            get {
                return ResourceManager.GetString("jplayer_playlist_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () {
        ///    getRQItem(docNo);
        ///});
        ///
        ///function renderItemContent() {
        ///    if (docAdr != &quot;PLAYLIST&quot;) {
        ///        $(&quot;#jquery_jplayer_1&quot;).jPlayer({
        ///            ready: function () {
        ///                $(&quot;.jp-title ul li&quot;).text(&quot;&quot;); //TODO: Track-Titel anzeigen
        ///                $(this).jPlayer(&quot;setMedia&quot;, {
        ///                    mp3: docAdr
        ///                }).jPlayer(&quot;play&quot;);
        ///            },
        ///            swfPath: &quot;/js&quot;,
        ///            supplied: &quot;mp3&quot;,
        ///            errorAlerts: false,
        ///            warningAle [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_audio_player {
            get {
                return ResourceManager.GetString("jquery_audio_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () {
        ///    getRQItem(docNo);
        ///});
        ///
        ///function renderItemContent() {
        ///    var w = $(&apos;#viewer_area&apos;).width();
        ///    var h = $(&apos;#viewport&apos;).height();
        ///
        ///    $(&apos;#viewer_area&apos;).media({
        ///        width: w,
        ///        height: h,
        ///        autoplay: true,
        ///        src: docAdr,
        ///        attrs: { attr1: &apos;attrValue1&apos;, attr2: &apos;attrValue2&apos; },  // object/embed attrs 
        ///        params: { param1: &apos;&apos;, param2: &apos;paramValue2&apos; }, // object params/embed attrs 
        ///        caption: false // supress caption text 
        ///    }, function [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_item_viewer {
            get {
                return ResourceManager.GetString("jquery_item_viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * jPlayer Plugin for jQuery JavaScript Library
        /// * http://www.jplayer.org
        /// *
        /// * Copyright (c) 2009 - 2013 Happyworm Ltd
        /// * Dual licensed under the MIT and GPL licenses.
        /// *  - http://www.opensource.org/licenses/mit-license.php
        /// *  - http://www.gnu.org/copyleft/gpl.html
        /// *
        /// * Author: Mark J Panaghiston
        /// * Version: 2.3.0
        /// * Date: 20th April 2013
        /// */
        ///
        ////* Code verified using http://www.jshint.com/ */
        ////*jshint asi:false, bitwise:false, boss:false, browser:true, curly:true, debug:false, eqeqeq:tr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_jplayer {
            get {
                return ResourceManager.GetString("jquery_jplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * jPlayerInspector Plugin for jPlayer Plugin for jQuery JavaScript Library
        /// * http://www.jplayer.org
        /// *
        /// * Copyright (c) 2009 - 2013 Happyworm Ltd
        /// * Dual licensed under the MIT and GPL licenses.
        /// *  - http://www.opensource.org/licenses/mit-license.php
        /// *  - http://www.gnu.org/copyleft/gpl.html
        /// *
        /// * Author: Mark J Panaghiston
        /// * Version: 1.0.4
        /// * Date: 29th January 2013
        /// *
        /// * For use with jPlayer Version: 2.2.19+
        /// *
        /// * Note: Declare inspector instances after jPlayer instances. ie., Other [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_jplayer_inspector {
            get {
                return ResourceManager.GetString("jquery_jplayer_inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * jPlayer Plugin for jQuery JavaScript Library
        /// * http://www.jplayer.org
        /// *
        /// * Copyright (c) 2009 - 2013 Happyworm Ltd
        /// * Dual licensed under the MIT and GPL licenses.
        /// *  - http://www.opensource.org/licenses/mit-license.php
        /// *  - http://www.gnu.org/copyleft/gpl.html
        /// *
        /// * Author: Mark J Panaghiston
        /// * Version: 2.3.0
        /// * Date: 20th April 2013
        /// */
        ///(function(b,f){&quot;function&quot;===typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],f):f(b.jQuery)})(this,function(b,f){b.fn.jPlayer=function(a){var c=&quot;string&quot;===typeof a,d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_jplayer_min {
            get {
                return ResourceManager.GetString("jquery_jplayer_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// * jQuery Media Plugin for converting elements into rich media content.
        /// *
        /// * Examples and documentation at: http://malsup.com/jquery/media/
        /// * Copyright (c) 2007-2010 M. Alsup
        /// * Dual licensed under the MIT and GPL licenses:
        /// * http://www.opensource.org/licenses/mit-license.php
        /// * http://www.gnu.org/licenses/gpl.html
        /// *
        /// * @author: M. Alsup
        /// * @version: 0.96 (23-MAR-2011)
        /// * @requires jQuery v1.1.2 or later
        /// * $Id: jquery.media.js 2460 2007-07-23 02:53:15Z malsup $
        /// *
        /// * Supported Media Pl [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_media {
            get {
                return ResourceManager.GetString("jquery_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () {
        ///    getRQItem(docNo);
        ///});
        ///
        ///function renderItemContent() {
        ///    $(&quot;#jquery_jplayer_1&quot;).jPlayer({
        ///        ready: function () {
        ///            $(this).jPlayer(&quot;setMedia&quot;, {
        ///                m4v: docAdr,
        ///                ogv: &quot;http://www.jplayer.org/video/ogv/Big_Buck_Bunny_Trailer_480x270.ogv&quot;,
        ///                poster: &quot;http://www.jplayer.org/video/poster/Big_Buck_Bunny_Trailer_480x270.png&quot;
        ///            }).jPlayer(&quot;play&quot;);
        ///        },
        ///        swfPath: &quot;/areas/itemviewer/scripts&quot;,
        ///        s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string jquery_video_player {
            get {
                return ResourceManager.GetString("jquery_video_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /* tables */
        ///.simple-user-table {
        ///	background-color: #CDCDCD;
        ///	margin:10px 0pt 15px;
        ///	width: 100%;
        ///	text-align: left;
        ///}
        ///.simple-user-table thead tr th, .simple-user-table tfoot tr th {
        ///	background-color: #e6EEEE !important;
        ///	border: 1px solid #FFF;
        ///	padding: 4px;
        ///}
        ///.simple-user-table thead tr .header {
        ///	cursor: pointer;
        ///}
        ///.simple-user-table tbody td {
        ///	
        ///	padding: 4px;
        ///	background-color: #FFF;
        ///	vertical-align: top;
        ///}
        ///.simple-user-table tbody tr.odd td {
        ///	background-color:#F0F0F6;
        ///}
        ///.simple-user-table thead t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string specialstyle {
            get {
                return ResourceManager.GetString("specialstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #viewer_area {
        ///    min-width: 95%;
        ///    margin: 5px 5px 5px 5px;
        ///}
        ///
        ///.bibinfo {
        ///    font-family: &apos;Courier New&apos;;
        ///    line-height: 1.5em;
        ///    margin: 10px 10px 10px 10px;
        ///}        ///
        ///#viewport .pure-u-2-3 {
        ///    min-height: 100%;
        ///}
        ///
        ///.jp-audio {
        ///    display: table;
        ///    margin: 0 auto;
        ///}        ///
        ///
        ///
        /// ähnelt.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;div id=&quot;viewer_area&quot;&gt;
        ///    &lt;div id=&quot;jp_container_1&quot; class=&quot;jp-video jp-video-360p&quot;&gt;
        ///        &lt;div class=&quot;jp-type-single&quot;&gt;
        ///            &lt;div id=&quot;jquery_jplayer_1&quot; class=&quot;jp-jplayer&quot;&gt;&lt;/div&gt;
        ///            &lt;div class=&quot;jp-gui&quot;&gt;
        ///                &lt;div class=&quot;jp-video-play&quot;&gt;
        ///                    &lt;a href=&quot;javascript:;&quot; class=&quot;jp-video-play-icon&quot; tabindex=&quot;1&quot;&gt;play&lt;/a&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;jp-interface&quot;&gt;
        ///                    &lt;div class=&quot;jp-progress&quot;&gt;
        ///                        &lt;div class= [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string video_player {
            get {
                return ResourceManager.GetString("video_player", resourceCulture);
            }
        }
    }
}
