//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcRQ.Scripts.HtmlFactoryScripts {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptPack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptPack() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcRQ.Scripts.HtmlFactoryScripts.ScriptPack", typeof(ScriptPack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var saveData = null;
        ///var verb = getUrlVar(&quot;verb&quot;);
        ///var itemId = &quot;&quot;;
        ///
        ///$(function () {
        ///    var editForm = new EditForm();
        ///
        ///    editForm.init();
        ///});
        ///
        ///function EditForm() {
        ///    this.init = function () {
        ///        if (!$(&quot;.edit-form&quot;))
        ///            return;
        ///        $(&quot;#btn-submit-item&quot;).click(submitItem);
        ///        $(&quot;#btn-reset&quot;).click(reset);
        ///        if (verb == &quot;edit&quot; || verb == &quot;copy&quot;) {
        ///            itemId = rqitemid(); // (rqitemid &lt; 10000) ? &quot;0&quot; + rqitemid : rqitemid;
        ///            getItem();
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string edit_rqitem_code {
            get {
                return ResourceManager.GetString("edit_rqitem_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;style&gt;
        ///    .edit-form {
        ///        position: relative;
        ///    }
        ///&lt;/style&gt;
        ///&lt;form id=&quot;EditForm&quot; class=&quot;edit-form&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;legend&gt;Eingabemaske&lt;/legend&gt;
        ///        &lt;span class=&quot;editor-label&quot;&gt;
        ///            &lt;label for=&quot;ID&quot;&gt;ID: &lt;/label&gt;&lt;span id=&quot;idval&quot;&gt;&lt;/span&gt;&lt;input id=&quot;ID&quot; name=&quot;ID&quot; type=&quot;hidden&quot; value=&quot;7699&quot; /&gt;
        ///            &lt;label for=&quot;DocNo&quot;&gt;Dok-Nr.: &lt;/label&gt;&lt;span id=&quot;doknrval&quot;&gt;&lt;/span&gt;&lt;input id=&quot;DocNo&quot; name=&quot;DocNo&quot; type=&quot;hidden&quot; value=&quot;07876&quot; /&gt;
        ///        &lt;/span&gt;
        ///		&lt;span class=&quot;editor-label&quot;&gt;&lt;label for=&quot;Ti [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string edit_rqitem_form {
            get {
                return ResourceManager.GetString("edit_rqitem_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die body {
        ///}
        /// ähnelt.
        /// </summary>
        internal static string edit_rqitem_style {
            get {
                return ResourceManager.GetString("edit_rqitem_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die //Ajax overlay 1.0
        ///// Author: Simon Ilett(at)aplusdesign.com.au
        /////* Descrip: Creates and inserts an ajax loader for ajax calls / timed events 
        /////* Date: 03/08/2011 
        ///function ajaxLoader(el, options) {
        ///    // Becomes this.options
        ///    var defaults = {
        ///        bgColor: &apos;#fff&apos;,
        ///        duration: 800,
        ///        opacity: 0.7,
        ///        classOveride: false
        ///    }
        ///    this.options = jQuery.extend(defaults, options);
        ///    this.container = $(el);
        ///
        ///    this.init = function () {
        ///        var container = this.co [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string rqui_helpers {
            get {
                return ResourceManager.GetString("rqui_helpers", resourceCulture);
            }
        }
    }
}
