//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcRQ.Scripts.HtmlFactoryScripts {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptPack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptPack() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcRQ.Scripts.HtmlFactoryScripts.ScriptPack", typeof(ScriptPack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var saveData = null;
        ///var verb = getUrlVar(&quot;verb&quot;);
        ///var itemId = &quot;&quot;;
        ///var compiledTemplate = &quot;&quot;;
        ///
        ///$(function () {
        ///    var editForm = new EditForm();
        ///
        ///    compiledTemplate = $.templates($(&quot;#tocTemplate&quot;).html());
        ///    editForm.init();
        ///});
        ///
        ///function EditForm() {
        ///    this.init = function () {
        ///        if (!$(&quot;.edit-form&quot;))
        ///            return;
        ///        $(&quot;#btn-submit-item&quot;).click(submitItem);
        ///        $(&quot;#btn-reset&quot;).click(reset);
        ///        $(&quot;#tocAttach&quot;).click(attachTOC);
        ///        if (verb == &quot;edit&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string edit_rqitem_code {
            get {
                return ResourceManager.GetString("edit_rqitem_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;style&gt;
        ///    .edit-form {
        ///        position: relative;
        ///    }
        ///&lt;/style&gt;
        ///&lt;div class=&quot;rq-ajax-wait&quot; style=&quot;display: none&quot;&gt;&lt;/div&gt;
        ///&lt;form id=&quot;EditForm&quot; class=&quot;edit-form pure-form&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;legend&gt;Eingabemaske&lt;/legend&gt;
        ///        &lt;span class=&quot;editor-label&quot;&gt;
        ///            &lt;label for=&quot;ID&quot;&gt;ID: &lt;/label&gt;&lt;span id=&quot;idval&quot;&gt;&lt;/span&gt;
        ///            &lt;label for=&quot;DocNo&quot;&gt;Dok-Nr.: &lt;/label&gt;&lt;span id=&quot;doknrval&quot;&gt;&lt;/span&gt;
        ///        &lt;/span&gt;
        ///		&lt;span class=&quot;editor-label&quot;&gt;&lt;label for=&quot;Title&quot;&gt;Titel&lt;/label&gt;&lt;/span&gt;
        ///		&lt;span class=&quot;editor- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string edit_rqitem_form {
            get {
                return ResourceManager.GetString("edit_rqitem_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /* edit-viewer styles*/
        ///.edit-form {
        ///    background-color: transparent;
        ///}
        ///
        ///.edit-dialog,
        ///.attach-toc-dialog {
        ///    display: none;
        ///}
        ///
        ///label {
        ///    font-size: 1.3em !important;
        ///    display: inline;
        ///}
        ///
        ///label[for=Title],
        ///label[for=Institutions],
        ///label[for=IndexTerms],
        ///label[for=AboutPersons] {
        ///    display: block;
        ///}
        ////*
        ///label[for=Volume],
        ///label[for=DocTypeCode] {
        ///    display: inline-block;
        ///}
        ///*/
        ///
        ////* hack: insert a line-break */
        ///label[for=Titel]:before,
        ///label[for=AboutTime]:before,
        ///labe [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string edit_rqitem_style {
            get {
                return ResourceManager.GetString("edit_rqitem_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var myInterval = false; // this variable will hold the interval and work as a flag
        ///var $win = $(window); //jquery win object
        ///var dimensions = [$win.width(), $win.height()]; //initial dimensions
        ///
        ///$(function () {
        ///    $(window).on(&quot;debouncedresize&quot;, function (event) {
        ///        dimensions[0] = $win.width(); //else keep the new dimensions
        ///        dimensions[1] = $win.height();
        ///        resizeToWindowHeight();
        ///    });
        ///});
        ///
        ///function resizeToWindowHeight() {
        ///    var height = dimensions[1] - 60;
        ///    var  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string rqui_helpers {
            get {
                return ResourceManager.GetString("rqui_helpers", resourceCulture);
            }
        }
    }
}
