//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5RQ.Areas.UserSettings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptPack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptPack() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvc5RQ.Areas.UserSettings.ScriptPack", typeof(ScriptPack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;form id=&quot;classtree-options-form&quot; class=&quot;pure-form-aligned&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;label for=&quot;classtree-options&quot;&gt;
        ///		{classtree-options}&lt;/label&gt;
        ///	&lt;input id=&quot;classtree-options&quot; type=&quot;checkbox&quot; /&gt;&lt;br/&gt;
        ///&lt;!--    &lt;a class=&quot;select-databases&quot; href=&quot;#&quot;&gt;{select-databases}&lt;/a&gt;--&gt;
        ///&lt;/fieldset&gt;
        ///&lt;/form&gt;
        /// ähnelt.
        /// </summary>
        internal static string classtree_options_form {
            get {
                return ResourceManager.GetString("classtree_options_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () {
        ///    var onlyShelvesCheckBox = new AddOnlyShelvesCheckBox();
        ///    onlyShelvesCheckBox.init(&quot;#classtree-options&quot;);
        ///    
        ///    //$(&quot;.select-databases&quot;).on(&quot;click&quot;, selectDatabases);
        ///});
        ///
        ///function AddOnlyShelvesCheckBox() {
        ///    var checkBox;
        ///
        ///    /* Initialize the only shelves check box and fill it with server data */
        ///    this.init = function (selector) {
        ///        // get check box
        ///        checkBox = $(selector);
        ///        // init the check box with server data  
        ///        $.post(HostAdres [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string classtree_options_management {
            get {
                return ResourceManager.GetString("classtree_options_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;form id=&quot;include-external-db-form&quot; class=&quot;pure-form-aligned&quot;&gt;
        ///&lt;fieldset&gt;
        ///	&lt;label for=&quot;include-external&quot;&gt;
        ///		{include-external}&lt;/label&gt;
        ///	&lt;input id=&quot;include-external&quot; type=&quot;checkbox&quot; /&gt;&lt;br/&gt;
        ///    &lt;a class=&quot;select-databases&quot; href=&quot;#&quot;&gt;{select-databases}&lt;/a&gt;
        ///&lt;/fieldset&gt;
        ///&lt;/form&gt;
        /// ähnelt.
        /// </summary>
        internal static string imclude_external_db_form {
            get {
                return ResourceManager.GetString("imclude_external_db_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () {
        ///    var includeExternalCheckBox = new AddIncludeExternalCheckBox();
        ///    includeExternalCheckBox.init(&quot;#include-external&quot;);
        ///    
        ///    $(&quot;.select-databases&quot;).on(&quot;click&quot;, selectDatabases);
        ///});
        ///
        ///function AddIncludeExternalCheckBox() {
        ///    var checkBox;
        ///
        ///    /* Initialize the include external check box and fill it with server data */
        ///    this.init = function (selector) {
        ///        // get check box
        ///        checkBox = $(selector);
        ///        // init the check box with server data  
        ///        [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string simple_query_options_management {
            get {
                return ResourceManager.GetString("simple_query_options_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*#simple-user-info {
        ///  padding: 15px 0;
        ///  text-align: center;
        ///  background-repeat: no-repeat;
        ///  background-position: 10px center;
        ///  position: relative;
        ///  color: #00529B;
        ///  position: fixed;
        ///  top: 0;
        ///  width: 100%;
        ///  filter: alpha(opacity=95);
        ///  -moz-opacity: 0.95;
        ///  opacity: 0.95;
        ///}
        ///
        ///#simple-user-info.error {
        ///  background-color: Yellow;
        ///}
        ///
        ///#simple-user-info.success {
        ///  background-color: Lime;
        ///}*/
        ///
        ///#add-user-form, #manage-roles-form {
        ///  display: inline-block;
        ///}
        ///
        ///.select-databases- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /* tables */
        ///.simple-user-table {
        ///	background-color: #CDCDCD;
        ///	margin:10px 0pt 15px;
        ///	width: 100%;
        ///	text-align: left;
        ///}
        ///.simple-user-table thead tr th, .simple-user-table tfoot tr th {
        ///	background-color: #e6EEEE !important;
        ///	border: 1px solid #FFF;
        ///	padding: 4px;
        ///}
        ///.simple-user-table thead tr .header {
        ///	cursor: pointer;
        ///}
        ///.simple-user-table tbody td {
        ///	
        ///	padding: 4px;
        ///	background-color: #FFF;
        ///	vertical-align: top;
        ///}
        ///.simple-user-table tbody tr.odd td {
        ///	background-color:#F0F0F6;
        ///}
        ///.simple-user-table thead t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string tablesorter_style {
            get {
                return ResourceManager.GetString("tablesorter_style", resourceCulture);
            }
        }
    }
}
