//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RQResources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RQResources.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die shelves only ähnelt.
        /// </summary>
        public static string classtree_options {
            get {
                return ResourceManager.GetString("classtree_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string classtree_options_h {
            get {
                return ResourceManager.GetString("classtree_options_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export publication project ähnelt.
        /// </summary>
        public static string da_export {
            get {
                return ResourceManager.GetString("da_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Article&gt;
        ///	&lt;Title&gt;Haftungsausschluss&lt;/Title&gt;
        ///	&lt;Sect1&gt;
        ///		&lt;Para&gt;
        ///			Die auf dieser Website zur Verfügung gestellten Informationen wurden nach bestem Wissen und Gewissen überprüft. 
        ///			Eine Haftung, Garantie und/ oder Gewährleistung für die Aktualität, Richtigkeit und Vollständigkeit der zur Verfügung 
        ///			gestellten Daten und Informationen wird jedoch ausdrücklich nicht übernommen.
        ///		&lt;/Para&gt;
        ///		&lt;Para&gt;
        ///			Alle Informationen können ohne vorherige Ankündigung gelös [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid data transmitted. ähnelt.
        /// </summary>
        public static string err_invalid_data {
            get {
                return ResourceManager.GetString("err_invalid_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not authorized to execute this function. ähnelt.
        /// </summary>
        public static string err_not_authorized {
            get {
                return ResourceManager.GetString("err_not_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requested item could not be found. ähnelt.
        /// </summary>
        public static string err_notfound {
            get {
                return ResourceManager.GetString("err_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This method has not yet been implemented. ähnelt.
        /// </summary>
        public static string err_notimplemented {
            get {
                return ResourceManager.GetString("err_notimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieval of data record failed. ähnelt.
        /// </summary>
        public static string err_rqds_get_item {
            get {
                return ResourceManager.GetString("err_rqds_get_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search request failed. ähnelt.
        /// </summary>
        public static string err_rqds_get_list {
            get {
                return ResourceManager.GetString("err_rqds_get_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add operation failed. ähnelt.
        /// </summary>
        public static string err_rqds_post_add {
            get {
                return ResourceManager.GetString("err_rqds_post_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update operation failed. ähnelt.
        /// </summary>
        public static string err_rqds_post_update {
            get {
                return ResourceManager.GetString("err_rqds_post_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unidentified error. ähnelt.
        /// </summary>
        public static string err_unknown {
            get {
                return ResourceManager.GetString("err_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error on processing the request. ähnelt.
        /// </summary>
        public static string errmessage {
            get {
                return ResourceManager.GetString("errmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FAQList&gt;
        ///	&lt;FAQItem&gt;
        ///		&lt;FAQQuestion&gt;
        ///			What is a Digital Library?
        ///		&lt;/FAQQuestion&gt;
        ///		&lt;FAQAnswer&gt;
        ///			A Digital Library is a focused collection of digital objects, including text, video, and audio, along with methods for access and retrieval, and for selection, organization and maintenance of the collection.&amp;lt;br/&amp;gt;&amp;lt;br/&amp;gt;(citation from: How to build a digital library, by Ian H. Witten and David Bainbridge)
        ///		&lt;/FAQAnswer&gt;
        ///	&lt;/FAQItem&gt;
        ///	&lt;FAQItem&gt;
        ///		&lt;FAQ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finalize ähnelt.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include ähnelt.
        /// </summary>
        public static string include_external {
            get {
                return ResourceManager.GetString("include_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External Databases ähnelt.
        /// </summary>
        public static string include_external_h {
            get {
                return ResourceManager.GetString("include_external_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not authorized to access this digital object. ähnelt.
        /// </summary>
        public static string itemView_access_denied {
            get {
                return ResourceManager.GetString("itemView_access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string link_home {
            get {
                return ResourceManager.GetString("link_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string link_privacy {
            get {
                return ResourceManager.GetString("link_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terms ähnelt.
        /// </summary>
        public static string link_terms {
            get {
                return ResourceManager.GetString("link_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die logoff ähnelt.
        /// </summary>
        public static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die logon ähnelt.
        /// </summary>
        public static string logon {
            get {
                return ResourceManager.GetString("logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catalogue ähnelt.
        /// </summary>
        public static string menu1 {
            get {
                return ResourceManager.GetString("menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string menu2 {
            get {
                return ResourceManager.GetString("menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shelves ähnelt.
        /// </summary>
        public static string menu3 {
            get {
                return ResourceManager.GetString("menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workplace ähnelt.
        /// </summary>
        public static string menu4 {
            get {
                return ResourceManager.GetString("menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        public static string menu5 {
            get {
                return ResourceManager.GetString("menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users ähnelt.
        /// </summary>
        public static string menu6 {
            get {
                return ResourceManager.GetString("menu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string menu7 {
            get {
                return ResourceManager.GetString("menu7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;Article&gt; 
        ///  &lt;Title&gt;Privacy Statement &lt;/Title&gt;
        ///  &lt;Sect1&gt; 
        ///	 &lt;Title&gt;&lt;/Title&gt;
        ///	 &lt;Para&gt;RiQuest is committed to protecting your privacy and developing
        ///		technology that gives you the most powerful and safe online experience. This
        ///		Statement of Privacy applies to the RiQuest Web site and governs data
        ///		collection and usage. By using the RiQuest website, you consent to the data
        ///		practices described in this statement.&lt;/Para&gt;
        ///  &lt;/Sect1&gt;
        ///  &lt;Sect1&gt;
        ///	 &lt;Title&gt; C [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query Fields ähnelt.
        /// </summary>
        public static string query_fields_h {
            get {
                return ResourceManager.GetString("query_fields_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add record ähnelt.
        /// </summary>
        public static string sa_add {
            get {
                return ResourceManager.GetString("sa_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export result list ähnelt.
        /// </summary>
        public static string sa_export {
            get {
                return ResourceManager.GetString("sa_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string sa_h {
            get {
                return ResourceManager.GetString("sa_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select databases ähnelt.
        /// </summary>
        public static string select_databases {
            get {
                return ResourceManager.GetString("select_databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio Recordings ähnelt.
        /// </summary>
        public static string sq_audio_documents {
            get {
                return ResourceManager.GetString("sq_audio_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weblinks ähnelt.
        /// </summary>
        public static string sq_bookmarks {
            get {
                return ResourceManager.GetString("sq_bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Audio ähnelt.
        /// </summary>
        public static string sq_digital_audio {
            get {
                return ResourceManager.GetString("sq_digital_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Documents ähnelt.
        /// </summary>
        public static string sq_digital_documents {
            get {
                return ResourceManager.GetString("sq_digital_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Video ähnelt.
        /// </summary>
        public static string sq_digital_video {
            get {
                return ResourceManager.GetString("sq_digital_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard Queries ähnelt.
        /// </summary>
        public static string sq_h {
            get {
                return ResourceManager.GetString("sq_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent Additions ähnelt.
        /// </summary>
        public static string sq_recent_additions {
            get {
                return ResourceManager.GetString("sq_recent_additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        /// </summary>
        public static string sq_video_documents {
            get {
                return ResourceManager.GetString("sq_video_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the personal digital library ähnelt.
        /// </summary>
        public static string subtitle {
            get {
                return ResourceManager.GetString("subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;Article&gt; 
        ///  &lt;Title&gt;Terms of Use&lt;/Title&gt;
        ///  &lt;Sect1&gt; 
        ///	 &lt;Title&gt;AGREEMENT BETWEEN USER AND RiQuest&lt;/Title&gt;
        ///	 &lt;Para&gt; The &lt;Emphasis&gt;RiQuest&lt;/Emphasis&gt; Web Site is comprised of various Web pages operated by
        ///		RiQuest. The RiQuest Web Site is offered to you conditioned on your acceptance
        ///		without modification of the terms, conditions, and notices contained herein.
        ///		Your use of the RiQuest Web Site constitutes your agreement to all such terms,
        ///		conditions, and [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RiQuest ähnelt.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error on storing in user database. ähnelt.
        /// </summary>
        public static string um_database_store_error {
            get {
                return ResourceManager.GetString("um_database_store_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid user role name.  ähnelt.
        /// </summary>
        public static string um_invalid_role_name {
            get {
                return ResourceManager.GetString("um_invalid_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No user roles defined. ähnelt.
        /// </summary>
        public static string um_no_roles_defined {
            get {
                return ResourceManager.GetString("um_no_roles_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No users found. ähnelt.
        /// </summary>
        public static string um_no_users_found {
            get {
                return ResourceManager.GetString("um_no_users_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
    }
}
